- graphql/api/domains/inference/inference.graphqls
- graphql/api/domains/inference/query.graphqls
- java/pom.xml
- java/src/main/java/io/worlds/api/model/Segment.java
- java/src/main/java/io/worlds/api/model/SegmentationOptionsInput.java
- java/src/main/java/io/worlds/api/model/SegmentationResponse.java
- java/src/main/java/io/worlds/api/model/SegmentationResult.java
- Add Segmentation Queries and related types and inputs
works: https://worlds-io.atlassian.net/browse/CE-3051
> Segmentation Queries

- graphql/api/domains/inference/inference.graphqls
- graphql/api/domains/inference/query.graphqls
- java/src/main/java/io/worlds/api/model/EmbeddingOptionsInput.java
- java/src/main/java/io/worlds/api/model/EmbeddingResponse.java
- java/src/main/java/io/worlds/api/model/EmbeddingResult.java
- Add embedding queries and related types and inputs
https://worlds-io.atlassian.net/browse/CE-3054
> Add embedding queries and related types and inputs

- graphql/api/domains/events/events.graphqls
- java/src/main/java/io/worlds/api/model/Event.java
Add a list of `videos` to `Event` responses.
[CE-2513]
[CE-2513]: https://worlds-io.atlassian.net/browse/CE-2513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-2513: Add videos response to events

- graphql/api/domains/detection/detection.graphqls
- graphql/api/domains/frame/frame.graphqls
- graphql/api/domains/track/track.graphqls
- java/src/main/java/io/worlds/api/model/Detection.java
- java/src/main/java/io/worlds/api/model/Frame.java
- java/src/main/java/io/worlds/api/model/Track.java
- Add `video` field to `Track` type
- Add `Frame` type
- Add `frame` field to `Detection` type
https://worlds-io.atlassian.net/browse/REQ-159
> Detection Frames

- graphql/api/domains/devices/device.graphqls
- java/src/main/java/io/worlds/api/model/Device.java
- Add `frameRate` field to `Device` type
https://worlds-io.atlassian.net/browse/CE-3121
> Add frameRate to Device

- graphql/api/domains/devices/device.graphqls
- graphql/api/domains/devices/mutation.graphqls
- java/src/main/java/io/worlds/api/model/CreateDeviceInput.java
- java/src/main/java/io/worlds/api/model/UpdateDeviceInput.java
Add mutation for create and update device.
[CE-3123]
[CE-3123]: https://worlds-io.atlassian.net/browse/CE-3123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-3123: Create and Update Mutations for Devices

- graphql/api/domains/detection/detection.graphqls
- graphql/api/domains/track/track.graphqls
- graphql/api/domains/zone/filter.graphqls
- java/src/main/java/io/worlds/api/model/Detection.java
- java/src/main/java/io/worlds/api/model/FilterZoneIntersectionInput.java
- java/src/main/java/io/worlds/api/model/Track.java
Adds tag, datasource to FilterZoneIntersectionInput
Adds zoneIntersections, geofenceIntersections to Track type
https://worlds-io.atlassian.net/browse/CE-2334
https://worlds-io.atlassian.net/browse/CE-2905
https://worlds-io.atlassian.net/browse/CE-2919
> Track Zone/Geofence intersections and datasource/tag filter for Zone

- graphql/api/domains/pointOfInterest/mutation.graphqls
- graphql/api/domains/pointOfInterest/pointOfInterest.graphqls
- java/src/main/java/io/worlds/api/model/CreatePointOfInterestInput.java
- java/src/main/java/io/worlds/api/model/PointOfInterest.java
- java/src/main/java/io/worlds/api/model/UpdatePointOfInterestInput.java
- Add `createPointOfInterest` mutation
- Add `updatePointOfInterest` mutation
https://worlds-io.atlassian.net/browse/CE-3125
https://worlds-io.atlassian.net/browse/CE-3126
> Add createPointOfInterest and updatePointOfInterest mutations

- graphql/api/domains/dataSource/dataSource.graphqls
- graphql/api/domains/dataSource/mutation.graphqls
- java/src/main/java/io/worlds/api/model/UpdateDataSourceInput.java
Add update data source mutation.
[CE-3122]
[CE-3122]: https://worlds-io.atlassian.net/browse/CE-3122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-3122: Add updateDataSource mutation

- graphql/api/domains/detection/detection.graphqls
Adds direction field to detection type
https://worlds-io.atlassian.net/browse/CE-3141
> adds direction to detection type

- graphql/api/domains/track/track.graphqls
- java/src/main/java/io/worlds/api/model/UpdateTrackInput.java
update all UpdateTrackInput fields  option (except id)
https://worlds-io.atlassian.net/browse/CE-3011
> updateTrack mutation partial updates

- graphql/api/domains/events/events.graphqls
makes all of the fields in UpdateEventInput nullable, except Id
https://worlds-io.atlassian.net/browse/CE-3010
> CE-3011: updateEvent Mutation: Partial Updates

- graphql/api/domains/detection/detection.graphqls
- graphql/api/domains/video/video.graphqls
- java/src/main/java/io/worlds/api/model/Detection.java
- java/src/main/java/io/worlds/api/model/Video.java
Deprecates zoneIds/geofenceIds for Detection type and replaces them with zones/geofences objects
https://worlds-io.atlassian.net/browse/REQ-164
> REQ-164 - Link Zone Information to Detection Subscription

- graphql/api/domains/detection/mutation.graphqls
Add `createDetections` mutation.
[CE-3251]
[CE-3251]: https://worlds-io.atlassian.net/browse/CE-3251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-3251: Add createDetections mutation

- graphql/api/domains/sensor/filter.graphqls
- graphql/api/domains/sensor/query.graphqls
- graphql/api/domains/sensor/util.graphqls
- java/src/main/java/io/worlds/api/model/FilterSensorInput.java
- java/src/main/java/io/worlds/api/model/SensorConnection.java
- java/src/main/java/io/worlds/api/model/SensorEdge.java
- java/src/main/java/io/worlds/api/model/SensorSort.java
- java/src/main/java/io/worlds/api/model/SensorSortField.java
Add schema for `sensors` query and associated types.
[CE-3252]
[CE-3252]: https://worlds-io.atlassian.net/browse/CE-3252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-3252: Sensors query

- graphql/api/domains/events/events.graphqls
- java/src/main/java/io/worlds/api/model/EventProperties.java
Add `tracks` list to `eventProperties`
[CE-3294]
[CE-3294]: https://worlds-io.atlassian.net/browse/CE-3294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-3294: Add tracks to event properties

- graphql/api/domains/events/events.graphqls
- java/src/main/java/io/worlds/api/model/CreateEventInput.java
- java/src/main/java/io/worlds/api/model/UpdateEventInput.java
Add `EventValidationInput` type to event create and update schemas
[CE-3291]
[CE-3291]: https://worlds-io.atlassian.net/browse/CE-3291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-3291: Add EventValidation to schema

- graphql/api/domains/detection/detection.graphqls
- graphql/api/domains/track/track.graphqls
- java/src/main/java/io/worlds/api/model/CreateDetectionInput.java
- java/src/main/java/io/worlds/api/model/TrackDetectionInput.java
Add optional `direction` float to detection mutations.
[CE-3304]
[CE-3304]: https://worlds-io.atlassian.net/browse/CE-3304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-3304: Add direction to detection mutations

- graphql/api/domains/video/video.graphqls
- java/src/main/java/io/worlds/api/model/Video.java
Add `frameRate` to `Video`.
[CE-3143]
[CE-3143]: https://worlds-io.atlassian.net/browse/CE-3143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-3143: add frame rate to video

- graphql/api/domains/events/filter.graphqls
- java/src/main/java/io/worlds/api/model/FilterEventInput.java
Rename `valid` filter to `validation`.
[CE-3343]
[CE-3343]: https://worlds-io.atlassian.net/browse/CE-3343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-3343: Rename valid filter to validation

- graphql/api/domains/detection/filter.graphqls
- java/src/main/java/io/worlds/api/model/FilterDetectionInput.java
Add `trackId` filter to `detections`.
[CE-3254]
[CE-3254]: https://worlds-io.atlassian.net/browse/CE-3254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-3254: Add trackId filter to detections

- graphql/api/domains/track/filter.graphqls
- java/src/main/java/io/worlds/api/model/FilterTrackInput.java
- java/src/main/java/io/worlds/api/model/FilterTrackMessageInput.java
Add `pointOfInterestId` filter to tracks.
[CE-3548]
[CE-3548]: https://worlds-io.atlassian.net/browse/CE-3548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-3548: Add point of interest filters to tracks

- graphql/api/domains/image/mutation.graphqls
Add `uploadImage` mutation using `UploadImageInput` from event image uploads.
[CE-3646]
[CE-3646]: https://worlds-io.atlassian.net/browse/CE-3646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-3646: Add create image mutation

- graphql/api/domains/chronicle/activity/activityChronicle.graphqls
- graphql/api/domains/chronicle/activity/filter.graphqls
- graphql/api/domains/chronicle/activity/mutation.graphqls
- graphql/api/domains/chronicle/activity/query.graphqls
- graphql/api/domains/chronicle/activity/subscription.graphqls
- graphql/api/domains/chronicle/activity/util.graphqls
- graphql/api/domains/chronicle/chronicle.graphqls
- graphql/api/domains/chronicle/event/eventChronicle.graphqls
- graphql/api/domains/chronicle/event/filter.graphqls
- graphql/api/domains/chronicle/event/mutation.graphqls
- graphql/api/domains/chronicle/event/query.graphqls
- graphql/api/domains/chronicle/event/subscription.graphqls
- graphql/api/domains/chronicle/event/util.graphqls
- graphql/api/domains/chronicle/filter.graphqls
- graphql/api/domains/chronicle/mutation.graphqls
- graphql/api/domains/chronicle/query.graphqls
- graphql/api/domains/chronicle/summary/filter.graphqls
- graphql/api/domains/chronicle/summary/mutation.graphqls
- graphql/api/domains/chronicle/summary/query.graphqls
- graphql/api/domains/chronicle/summary/subscription.graphqls
- graphql/api/domains/chronicle/summary/summaryChronicle.graphqls
- graphql/api/domains/chronicle/summary/util.graphqls
- graphql/api/domains/chronicle/util.graphqls
- graphql/api/filter.graphqls
- graphql/api/root.graphqls
Add an `@experimental` directive and add to chronicle schemas.
> Add experimental directive

- graphql/api/domains/devices/device.graphqls
- java/src/main/java/io/worlds/api/model/Device.java
Add `lastHeartbeat` to `Device` type
[CE-3828]
[CE-3828]: https://worlds-io.atlassian.net/browse/CE-3828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-3828: Add lastHeartbeat

- graphql/api/domains/track/filter.graphqls
- java/src/main/java/io/worlds/api/model/FilterTrackInput.java
- java/src/main/java/io/worlds/api/model/FilterTrackMessageInput.java
Add `dataSourceType` to tracks query and subscription.
[CE-4014]
[CE-4014]: https://worlds-io.atlassian.net/browse/CE-4014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-4014: Add schema for tracks filter dataSourceType

- graphql/api/domains/chronicle/summary/summaryChronicle.graphqls
- java/src/main/java/io/worlds/api/model/SummaryChronicle.java
Fix typo in `eventChronicles` type.
[CE-4014]
[CE-4014]: https://worlds-io.atlassian.net/browse/CE-4014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CE-4014: Fix typo 'SummaryChronicles' in eventChronicles type

- graphql/api/domains/dataSource/dataSource.graphqls
- graphql/api/domains/dataSource/filter.graphqls
- java/src/main/java/io/worlds/api/model/CreateDataSourceInput.java
- java/src/main/java/io/worlds/api/model/DataSource.java
- java/src/main/java/io/worlds/api/model/FilterDataSourceInput.java
- java/src/main/java/io/worlds/api/model/UpdateDataSourceInput.java
Support for adding/modifying labels to data sources
https://worlds-io.atlassian.net/browse/CE-4020
> CE-4020: Data source labels
